'use client';
import Link from 'next/link';
import {ArrowLeft,ArrowRight,Check,Loader2,MessageCircle} from 'lucide-react';
import {FormEvent,useState} from 'react';

export default function ContactPage(){
 const [form,setForm]=useState({name:'',phone:'',email:'',message:''}); const [status,setStatus]=useState<'idle'|'loading'|'success'|'error'>('idle'); const [error,setError]=useState('');
 async function submit(e:FormEvent){e.preventDefault();setStatus('loading');setError('');try{const r=await fetch('/api/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to send message.');setStatus('success');}catch(err){setStatus('error');setError(err instanceof Error?err.message:'Something went wrong.')}}
 if(status==='success')return <main className="container grid min-h-[65vh] place-items-center py-20 text-center"><div className="max-w-lg"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-slate-950 text-white"><Check/></div><p className="eyebrow mt-6">Message sent</p><h1 className="mt-3 text-4xl font-semibold tracking-tight">We’ll get back to you.</h1><p className="mt-4 text-sm leading-7 text-slate-500">Your message has been received. For a faster response, you can also reach Vendly directly on WhatsApp.</p><a href={process.env.NEXT_PUBLIC_WHATSAPP_NUMBER?`https://wa.me/${process.env.NEXT_PUBLIC_WHATSAPP_NUMBER}`:"#"} className="btn-primary mt-7 inline-flex"><MessageCircle className="h-4 w-4"/> WhatsApp Vendly</a></div></main>;
 return <main className="container py-10"><Link href="/shop" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-[rgba(0,0,0,0.45)]"><ArrowLeft size={14}/> Back to shop</Link><div className="mt-12 grid gap-14 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="eyebrow">Customer service</p><h1 className="mt-4 text-5xl font-bold tracking-[-.07em] md:text-6xl">Talk to Vendly.</h1><p className="mt-6 max-w-md text-sm leading-7 text-[rgba(0,0,0,0.55)]">Questions about a product, availability, delivery or your order? Send us a message and our team can follow up.</p><a href={process.env.NEXT_PUBLIC_WHATSAPP_NUMBER?`https://wa.me/${process.env.NEXT_PUBLIC_WHATSAPP_NUMBER}`:"#"} className="mt-8 inline-flex items-center gap-2 rounded-full border border-[rgba(0,0,0,0.15)] px-5 py-3 text-sm font-bold"><MessageCircle size={16}/> WhatsApp directly</a></div><form onSubmit={submit} className="space-y-5 rounded-2xl border border-[rgba(0,0,0,0.1)] p-6 md:p-8"><Field label="Full name"><input required className="input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Phone number"><input required type="tel" className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="Email address"><input type="email" className="input" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field></div><Field label="How can we help?"><textarea required rows={7} maxLength={2000} className="input h-auto py-3" value={form.message} onChange={e=>setForm({...form,message:e.target.value})}/></Field>{status==='error'&&<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}<button disabled={status==='loading'} className="btn-primary w-full disabled:opacity-50">{status==='loading'?<><Loader2 className="h-4 w-4 animate-spin"/> Sending…</>:<>Send message <ArrowRight className="h-4 w-4"/></>}</button></form></div></main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-xs font-semibold text-[rgba(0,0,0,0.5)]">{label}</span>{children}</label>}
