'use client';
import Link from 'next/link';import {Menu,Search,ShoppingBag,X,Heart,ArrowUpRight,UserRound} from 'lucide-react';import {useState} from 'react';import {useCart} from './CartProvider';import {useWishlist} from './WishlistProvider';
export default function Header(){const [open,setOpen]=useState(false);const [searchOpen,setSearchOpen]=useState(false);const {count}=useCart();const {ids}=useWishlist();return <>
<header className="sticky top-0 z-50 border-b border-black/[.07] bg-[#faf9f6]/90 backdrop-blur-2xl"><div className="container flex h-[72px] items-center justify-between">
<Link href="/" className="text-[25px] font-black tracking-[-.08em]">vendly<span className="text-black/25">.</span></Link>
<nav className="hidden items-center gap-7 text-[13px] font-semibold md:flex"><Link className="nav-link" href="/shop">Shop</Link><Link className="nav-link" href="/category/Fashion">Fashion</Link><Link className="nav-link" href="/category/Footwear">Footwear</Link><Link className="nav-link" href="/category/Bags">Bags</Link><Link className="nav-link" href="/category/Beauty">Beauty</Link></nav>
<div className="flex items-center gap-1"><button onClick={()=>setSearchOpen(true)} aria-label="Search Vendly" className="icon-btn"><Search size={18}/></button><Link href="/account" aria-label="Account" className="icon-btn"><UserRound size={18}/></Link><Link href="/wishlist" aria-label="Wishlist" className="icon-btn relative"><Heart size={18}/>{ids.length>0&&<span className="count-dot">{ids.length>9?'9+':ids.length}</span>}</Link><Link href="/cart" aria-label="Cart" className="icon-btn relative"><ShoppingBag size={18}/>{count>0&&<span className="count-dot">{count>9?'9+':count}</span>}</Link><button onClick={()=>setOpen(!open)} className="icon-btn md:hidden" aria-label="Open menu">{open?<X size={19}/>:<Menu size={19}/>}</button></div></div>
{open&&<nav className="border-t border-black/[.07] bg-[#faf9f6] px-4 py-6 md:hidden"><div className="grid gap-1 text-[22px] font-semibold tracking-tight">{['Shop','Fashion','Footwear','Bags','Watches','Beauty'].map(c=><Link key={c} onClick={()=>setOpen(false)} className="rounded-xl px-2 py-2.5 hover:bg-black/5" href={c==='Shop'?'/shop':`/category/${c}`}>{c}</Link>)}<Link onClick={()=>setOpen(false)} className="mt-3 flex items-center justify-between border-t border-black/10 px-2 pt-5 text-base" href="/contact">Customer service <ArrowUpRight size={17}/></Link></div></nav>}
</header>
{searchOpen&&<SearchOverlay close={()=>setSearchOpen(false)}/>}</>}
function SearchOverlay({close}:{close:()=>void}){const [q,setQ]=useState('');return <div className="fixed inset-0 z-[100] bg-black/45 p-3 backdrop-blur-md" onMouseDown={close}><div onMouseDown={e=>e.stopPropagation()} className="mx-auto mt-3 max-w-2xl overflow-hidden rounded-3xl border border-black/10 bg-[#faf9f6] shadow-2xl md:mt-12"><div className="flex items-center gap-3 border-b border-black/10 p-5"><Search className="text-black/35" size={20}/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search the Vendly collection…" className="flex-1 bg-transparent text-lg outline-none"/><button onClick={close} className="rounded-full bg-black/5 p-2"><X size={17}/></button></div><div className="p-5"><p className="eyebrow text-black/35">Explore</p><div className="mt-4 flex flex-wrap gap-2">{['Fashion','Footwear','Bags','Watches','Beauty'].map(x=><Link onClick={close} key={x} href={`/category/${x}`} className="chip">{x}</Link>)}</div><Link onClick={close} href={q.trim()?`/shop?q=${encodeURIComponent(q)}`:'/shop'} className="mt-6 flex items-center justify-between rounded-2xl bg-black px-5 py-4 text-sm font-bold text-white">{q.trim()?`Search for “${q}”`:'Browse everything'}<ArrowUpRight size={17}/></Link></div></div></div>}
