'use client';
import {useEffect,useState} from 'react';
import {ImagePlus,Save,Sparkles} from 'lucide-react';
import MediaUploader from './MediaUploader';
import MultiImageUploader from './MultiImageUploader';
export default function ProductForm({initial}:{initial?:any}){
 const [form,setForm]=useState({name:initial?.name||'',slug:initial?.slug||'',description:initial?.description||'',price:initial?.price||'',oldPrice:initial?.oldPrice||'',stock:initial?.stock??0,categoryId:initial?.categoryId||'',featured:initial?.featured||false,isPreorder:initial?.isPreorder||false,preorderNote:initial?.preorderNote||'',imageUrls:(initial?.images||[]).map((i:any)=>i.url) as string[],videoUrl:initial?.videos?.[0]?.url||''});
 const [categories,setCategories]=useState<any[]>([]); const [message,setMessage]=useState(''); const [saving,setSaving]=useState(false);
 useEffect(()=>{fetch('/api/admin/categories').then(r=>r.json()).then(d=>setCategories(d.categories||[])).catch(()=>{})},[]);
 const set=(k:string,v:any)=>setForm(x=>({...x,[k]:v}));
 async function save(e:any){e.preventDefault();setSaving(true);setMessage('Saving securely…');const url=initial?`/api/admin/products/${initial.id}`:'/api/admin/products';try{const r=await fetch(url,{method:initial?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();setMessage(r.ok?'Saved successfully.':(d.error||'Could not save.'));}catch{setMessage('Network error. Please try again.')}finally{setSaving(false)}}
 return <form onSubmit={save} className="space-y-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8">
  <div className="rounded-2xl bg-slate-950 p-5 text-white"><div className="flex items-center gap-3"><Sparkles size={18}/><div><p className="text-sm font-semibold">Premium catalogue setup</p><p className="mt-1 text-xs text-slate-400">Build the product around confidence: strong imagery first, motion where it helps.</p></div></div></div>
  <div><p className="eyebrow text-slate-400">Core information</p><div className="mt-4 grid gap-5 md:grid-cols-2"><label className="text-sm font-medium">Name<input className="input mt-2" required value={form.name} onChange={e=>set('name',e.target.value)}/></label><label className="text-sm font-medium">Slug<input className="input mt-2" required value={form.slug} onChange={e=>set('slug',e.target.value)}/></label><label className="text-sm font-medium">Price (₦)<input className="input mt-2" type="number" min="0" step="0.01" required value={form.price} onChange={e=>set('price',e.target.value)}/></label><label className="text-sm font-medium">Old price<input className="input mt-2" type="number" min="0" step="0.01" value={form.oldPrice} onChange={e=>set('oldPrice',e.target.value)}/></label><label className="text-sm font-medium">Stock<input className="input mt-2" type="number" min="0" required value={form.stock} onChange={e=>set('stock',e.target.value)}/></label><label className="text-sm font-medium">Category<select className="input mt-2" required value={form.categoryId} onChange={e=>set('categoryId',e.target.value)}><option value="">Select category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div></div>
  <label className="block text-sm font-medium">Description<textarea className="input mt-2 min-h-32" maxLength={3000} value={form.description} onChange={e=>set('description',e.target.value)}/></label>
  <div><p className="eyebrow text-slate-400">Store media</p><div className="mt-4 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-slate-200 p-4"><p className="text-sm font-semibold">Product images</p><p className="mt-1 text-xs text-slate-400">Up to 10 photos — the first is the main image shown everywhere.</p><div className="mt-4"><MultiImageUploader images={form.imageUrls} onChange={u=>set('imageUrls',u)}/></div></div><div className="rounded-2xl border border-slate-200 p-4"><p className="text-sm font-semibold">Optional listing video</p><p className="mt-1 text-xs text-slate-400">Shown only on the product page, with the main image as its poster.</p><div className="mt-4"><MediaUploader kind="video" value={form.videoUrl} onUploaded={u=>set('videoUrl',u)} onRemove={()=>set('videoUrl','')}/></div></div></div></div>
  <div className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><label className="flex items-center gap-3 text-sm font-medium"><input type="checkbox" checked={form.isPreorder} onChange={e=>set('isPreorder',e.target.checked)}/> Available for preorder <span className="font-normal text-slate-400">(shown to customers regardless of stock count)</span></label>{form.isPreorder&&<label className="mt-3 block text-sm font-medium">Preorder note (optional)<input className="input mt-2" placeholder="e.g. Ships in 3 weeks" maxLength={140} value={form.preorderNote} onChange={e=>set('preorderNote',e.target.value)}/></label>}</div>
  <div className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4"><span className="grid h-9 w-9 place-items-center rounded-xl bg-white"><ImagePlus size={17}/></span><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.featured} onChange={e=>set('featured',e.target.checked)}/> Feature this product in curated sections</label></div>
  <div className="flex flex-col gap-3 border-t pt-5 sm:flex-row sm:items-center sm:justify-between"><span className="text-sm text-slate-500">{message}</span><button disabled={saving} className="btn-primary disabled:cursor-not-allowed disabled:opacity-60"><Save size={16}/>{saving?'Saving…':'Save product'}</button></div>
 </form>
}
